name: 'Terraform Test'

on:
  push:
#   pull_request:
# # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  plan-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.NIHR_GITHUB_ACTIONS_IAM_ID }}
        aws-secret-access-key: ${{ secrets.NIHR_GITHUB_ACTIONS_IAM_SECRET }}
        aws-region: eu-west-2
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      run: |
           terraform init -backend-config="bucket=crnccd-s3-terraform-state" -backend-config="key=frf/dev/terraform.tfstate"
        
    - name: Terraform Validate
      run: |
           terraform validate

    - name: Terraform Format
      run: |
           terraform fmt

    - name: Terraform Plan - dev
      run: |
        echo "Check Plan"
        terraform plan -var="env=dev" -no-color > dev-plan.tfplan
        cat dev-plan.tfplan

    - uses: actions/upload-artifact@master
      with:
        name: dev-plan
        path: dev-plan.tfplan

    - name: Terraform Plan - dev
      run: |
        echo "Check Plan"
        terraform plan -var="env=dev" -no-color > dev-plan.tfplan
        cat dev-plan.tfplan

    - uses: actions/upload-artifact@master
      with:
        name: dev-plan
        path: dev-plan.tfplan

    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: ynasser25
        minimum-approvals: 1
        issue-title: "Deploying dev"
        issue-body: "Please approve or deny the deployment"
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: ''
        additional-denied-words: ''

    # - name: Request Approval for dev Deployment
    #   if: always()
    #   uses: wei/cancel-action@v1
    #   env:
    #     PLAN_FILE: ${{ steps['Terraform Plan - dev'].outputs.plan_file }}
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     approval_context: 'Please review the terraform plan and approve for deployment to dev'
    #     reviewers: 'ynasser25'
    #     approval_label: 'terraform/dev'

    - name: Terraform Apply - dev
      if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && contains(github.event.head_commit.message, 'approved'))
      run: |
        echo "Applying Plan"
        terraform apply -var="env=dev" -no-color -auto-approve "dev-plan.tfplan"

  # deploy-dev:
  #   runs-on: ubuntu-latest
  #   needs: plan-dev
  #   environment: DEV
  #   steps:

  #   - name: Configure AWS Credentials
  #     uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_VS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_VS_ACCESS_KEY_SECRET }}
  #       aws-region: eu-west-2
        
  #   - name: Terraform Init
  #     run: |
  #          terraform init -backend-config="bucket=dte-env-terraform-code" -backend-config="key=terraform.tfstate"
        
  #   - name: Terraform Validate
  #     run: |
  #          terraform validate

  #   - name: Terraform Format
  #     run: |
  #          terraform fmt
        
  #   - name: Terraform Workspace
  #     run: |
  #          terraform workspace select dev

  #   - uses: actions/download-artifact@master
  #     with:
  #       name: dev-plan
  #       path: dev-plan.tfplan
           
  #   - name: Terraform Apply - dev
  #     run: |
  #       echo "Applying Plan"
  #       terraform apply -var="env=dev" -no-color -auto-approve "dev-plan.tfplan"